### PR TITLE
Add an option for mythic raid

### PR DESCRIPTION
**Pull request by Elnarfim**
It shows 4 groups only when you're in mythic raid and every groups are shown when you're not in mythic raid (other difficulty or not instance)

### CODE REVIEW

**Comment by doadin** [comment]
There was a change made before to showing and hiding groups in raid and it messed up showing groups in CN, have you tested this in both current raids on all difficulties?

**Comment by Elnarfim** [comment]
It could be messed up when some players who are in 5~8 groups and they're in same instance

But It is good to check which players are in instance and has flexibility for making 5~6 groups

**Comment by doadin** [comment]
It looks like some of the other options at the very least showWrongZone = "MYTHIC" are affected, I think it would be more ideal,a t least for now to have this new way seperate, of the others.

**Comment by doadin** [comment]
83bfdefd7ecf5e37fd5731b6e29167b5a54a75b8

**Pull request closed without merging**
